class TransformerCheckpointKey:
    MODEL = 'model'
    OPTIMIZER = 'optimizer'
    SCHEDULER = 'scheduler'
    HYPER_PARAMS = 'hyper_params'
    TEXT_PROCESSOR = 'text_processor'
    ENCODER_TEXT_PROCESSOR = 'encoder_text_processor'
    DECODER_TEXT_PROCESSOR = 'decoder_text_processor'
    ITERATION = 'iteration'
    EPOCH = 'epoch'